resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- deployment.yaml
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- service.yaml
- mutating_webhook_configuration.yaml
